name: Multi-Version
api: 3.0.0
version: 1.2
main: NamelessLeaf\Creative\Main
description: Allows players with different versions of mcpe or mcbe to join
website: github.com/NamelessLeaf/Multi-Version/edit/main
load: STARTUP
